const instagramFeed = [
    {
      id: 1,
      username: "food.explorer",
      time: "1h",
      profileImg: "https://picsum.photos/100?random=1",
      postImg: "https://picsum.photos/800/600?random=1",
      mutualFrndImg1: "https://picsum.photos/100?random=2",
      mutualFrndImg2: "https://picsum.photos/100?random=3",
      likeCount: "2, 00, 000",
      caption: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      commentCount: "100",
    },
    {
      id: 2,
      username: "nature.lover",
      time: "1h",
      profileImg: "https://picsum.photos/100?random=4",
      postImg: "https://picsum.photos/900/700?random=1",
      mutualFrndImg1: "https://picsum.photos/100?random=5",
      mutualFrndImg2: "https://picsum.photos/100?random=6",
      likeCount: "2, 00, 000",
      caption: "Many tourists came to Nepal from all over the world to explore the beauty of the land & see the amazing natural places.",
      commentCount: "100",
    },
    {
      id: 3,
      username: "reelsofworld",
      time: "1h",
      profileImg: "https://picsum.photos/100?random=7",
      postImg: "https://picsum.photos/1000/800?random=1",
      mutualFrndImg1: "https://picsum.photos/100?random=8",
      mutualFrndImg2: "https://picsum.photos/100?random=9",
      likeCount: "2, 00, 000",
      caption: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      commentCount: "100",
    },
    {
      id: 4,
      username: "carlover",
      time: "1h",
      profileImg: "https://picsum.photos/100?random=10",
      postImg: "https://picsum.photos/800/600?random=2",
      mutualFrndImg1: "https://picsum.photos/100?random=11",
      mutualFrndImg2: "https://picsum.photos/100?random=12",
      likeCount: "2, 00, 000",
      caption: "Many tourists came to Nepal from all over the world to explore the beauty of the land & see the amazing natural places.",
      commentCount: "100",
    },
    {
      id: 5,
      username: "godness",
      time: "1h",
      profileImg: "https://picsum.photos/100?random=13",
      postImg: "https://picsum.photos/900/700?random=2",
      mutualFrndImg1: "https://picsum.photos/100?random=14",
      mutualFrndImg2: "https://picsum.photos/100?random=15",
      likeCount: "2, 00, 000",
      caption: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      commentCount: "100",
    },
  ];
  
  export default instagramFeed;
  